### ISSUE TITLE
Controlled list for tool roles

### ISSUE THREAD

**Issue by kobbejager** [E-RIHS/schema#12]
The Method schema contains a list of tools (equipment or software), and for each tool there is a tool role. This is currently still an examples list (which is not supported in Cordra/Jsoneditor). Does this need to be a controlled list?

```json
"tool_role": {
    "title": "Tool Role",
    "type": "string",
    "examples": [
        "Main Equipment",
        "Detector",
        "Data Processor",
        "Peak Detector"
    ]
}
```

**Comment by jpadfield** [comment]
It should probably be a controlled list, but I am not sure what level of granularity is needed here. Perhaps we might just define it as free text and then look to generate a list based on the terms people use?

**Comment by jpadfield** [comment]
How do these look:

URI | skos:prefLabel@en | skos:definition@en | skos:broader | skos:exactMatch
-- | -- | -- | -- | --
  | Detector | Device used to detect changes in physical or chemical quantities |   |  
  | Spectroscopic detector | Detector used for identifying materials by measuring their spectral properties | Detector |  
  | Imaging detector | Device that captures visual information for analysis | Detector |  
  | Environmental sensor | Device that monitors environmental conditions | Sensor |  
  | Analyser | Device or software that examines data or samples to derive conclusions |   |  
  | Spectral analysis | Technique used to determine the composition or physical properties of substances based on spectral data | Analyser |  
  | Image Analyser | Software or device that processes and analyzes imagery data | Analyser |  
  | Statistical Analyser | Tool used for analyzing data sets to identify trends and patterns | Analyser |  
  | Sampler | Device that collects samples for analysis |   |  
  | Micro-sampler | Device designed for collecting small quantity samples | Sampler |  
  | Sample processor | Device or software that prepares samples for analysis | Sampler |  
  | Encoder/Decoder | Tools used for encoding and decoding data |   |  
  | Signal processor | Device or software that processes electronic signals |   |  
  | Modeller | Software or tool used for creating representations of physical systems |   |  
  | Material modeller | Tool used to simulate and analyze material properties | Modeller |  
  | Structural modeller | Software used for simulating structural behavior | Modeller |  
  | Environmental modeller | Tool used for simulating environmental conditions and impacts | Modeller |  
  | Visualizer | Software or device that creates visual representations of data or models |   |  
  | 3D renderer | Software that produces image or animation from a model | Visualizer |  
  | Virtual/Augmented visualizer | Tools for creating virtual or augmented reality experiences | Visualizer |  
  | Graphical user interface | Software interface that allows users to interact through graphical icons |   |  
  | Archiver | Software or system used for preserving digital files |   |  
  | Data storage | Technologies and devices for storing data | Archiver |  
  | Metadata management | Tools for handling data about other data | Archiver |  
  | Digital preservation | Activities aimed at ensuring long-term access to digital data | Archiver |  
  | Communicator | Tools used for data transmission and communication |   |  
  | Data transmitter | Device or software used for sending data between systems | Communicator |  
  | Remote access | Technologies that allow users to access systems from a distance | Communicator |  
  | Collaboration | Tools and platforms that facilitate cooperative work | Communicator |  
  | Controller | Devices or software used for managing the operation of other devices |   |  
  | Instrument control | Software or devices for controlling analytical instruments | Controller |  
  | Environmental control | Systems for regulating environmental conditions | Controller |  
  | Process automation | Technologies for automating operational processes | Controller |  
  | Calibrator | Devices or software used for adjusting the accuracy of instruments |   |  
  | Instrument calibration | Process of adjusting and verifying the accuracy of an instrument | Calibrator |  
  | Data normalization | Techniques for adjusting and standardizing data | Calibrator |  
  | Quality assurance | Processes aimed at maintaining the quality of the analysis | Calibrator |  
  | Sensor | Device that detects or measures physical properties and records, indicates, or otherwise responds to it |   |

**Comment by jpadfield** [comment]
Start with this one:

URI | skos:prefLabel@en | skos:definition@en | skos:broader | skos:exactMatch
-- | -- | -- | -- | --
  | Detector | Device used to detect changes in physical or chemical quantities |   |  
  | Spectroscopic detector | Detector used for identifying materials by measuring their spectral properties | Detector |  
  | Imaging detector | Device that captures visual information for analysis | Detector |  
  | Environmental sensor | Device that monitors environmental conditions | Sensor |  
  | Analyser | Device or software that examines data or samples to derive conclusions |   |  
  | Spectral analyser | Technique used to determine the composition or physical properties of substances based on spectral data | Analyser |  
  | Image Analyser | Software or device that processes and analyzes imagery data | Analyser |  
  | Statistical Analyser | Tool used for analyzing data sets to identify trends and patterns | Analyser |  
  | Sampler | Device that collects samples for analysis |   |  
  | Micro-sampler | Device designed for collecting small quantity samples | Sampler |  
  | Sample processor | Device or software that prepares samples for analysis | Sampler |  
  | Encoder/Decoder | Tools used for encoding and decoding data |   |  
  | Data processor | Device or software that processes data |   |  
  | Signal processor | Device or software that processes electronic signals | Data Processor   |  
  | Modeller | Software or tool used for creating representations of physical systems |   |  
  | Material modeller | Tool used to simulate and analyze material properties | Modeller |  
  | Structural modeller | Software used for simulating structural behavior | Modeller |  
  | Environmental modeller | Tool used for simulating environmental conditions and impacts | Modeller |  
  | Visualizer | Software or device that creates visual representations of data or models |   |  
  | 3D renderer | Software that produces image or animation from a model | Visualizer |  
  | Virtual/Augmented visualizer | Tools for creating virtual or augmented reality experiences | Visualizer |  
  | Graphical user interface | Software interface that allows users to interact through graphical icons |   |  
  | Archiver | Software or system used for preserving digital files |   |  
  | Communicator | Tools used for data transmission and communication |   |  
  | Data transmitter | Device or software used for sending data between systems | Communicator |  
  | Collabrator | Tools and platforms that facilitate cooperative work | Communicator |  
  | Controller | Devices or software used for managing the operation of other devices |   |  
  | Instrument controler | Software or devices for controlling analytical instruments | Controller |  
  | Environmental controler | Systems for regulating environmental conditions | Controller |  
  | Calibrator | Devices or software used for adjusting the accuracy of instruments |   |  
  | Instrument calibrator | Process of adjusting and verifying the accuracy of an instrument | Calibrator |  
  | Data normaliser | Techniques for adjusting and standardizing data | Calibrator |   
  | Sensor | Device that detects or measures physical properties and records, indicates, or otherwise responds to it |   |

**Comment by jpadfield** [comment]
URI | skos:prefLabel@en | skos:definition@en | skos:broader | skos:exactMatch
-- | -- | -- | -- | --
| | Hazard Detector | Tools that identify potential dangers such as gas leaks, radiation, or toxic chemicals. | Detector |
| | Environmental Monitor | Instruments used to assess environmental conditions like air quality, noise levels, or water purity. | Sensor |
| | Condition Monitor | Equipment for monitoring the state and performance of machinery to predict and prevent failures. | Sensor |
| | Emergency Sensor | Sensors used to alert people about emergencies, including evacuation alarms and warning lights. | Sensor |
| | Position Monitor | Sensors used to monitor and record the location and position of equipment and the relevant subjects of study | Sensor |
| | Vibration Monitor | Detects and measures vibration levels in machinery to predict failures. | Detector |
| | Examination or Activity Recorder | Captures audio, video, or digital records of examinations for review or archival purposes. |  |
