### ISSUE TITLE
Check method_statement parameter

### ISSUE THREAD

**Issue by jpadfield** [E-RIHS/schema#2]
https://github.com/E-RIHS/schema/blob/bbb20d71604205138ad61c327c5ecdbcf62b6b47/equipment-v0.5.schema.json#L10

@kobbejager I think this one might be an old copy paste issue that we need to remove. As we moved this info to the Method model.

The same in the Software schema: https://github.com/E-RIHS/schema/blob/bbb20d71604205138ad61c327c5ecdbcf62b6b47/software-v0.5.schema.json#L10C11-L10C30

**Comment by kobbejager** [comment]
The Equipment schema hasn't been migrated to Cordra yet. I'll leave this issue open as a reminder to remove it then (although Cordra will complain about it anyway).

Would it be a good idea to copy all of the schemas in Cordra in this repository. That would allow us to discuss issues in them. They are already labeled `v1.0`, but still moving targets at the moment, but since they aren't used in production, I can live with that.

I would also propose to move all `v0.x `versions in a 'draft' subfolder. This breaks the embedded `$id` property, but they are not used anywhere in production and won't work in Cordra anyway. What do you think @jpadfield?

**Comment by jpadfield** [comment]
I think it could be good to ensure we have an up to date copy of the schema here.

I also think it would be good to consider how we promote the current versions vs older ones. Moving them to an archive would make things cleaner but that approach would be a problem in the future when they do start to be used - what do we do with v1.1 or what do we do when we move to v2.0?

Now we have always agreed to reference the files via https://e-rihs.io/schema/* so perhaps we need to rethink how that is done. 

We have a discussion similar to the one we have had in relation to our models.

1. We could organise models into folders and then have all of the different version in one place, but it would be cleaner than having them all of the version of all of the different schema in the same folder.
2. We could leave them all in the same folder but change the README in a similar way to the models - promoting the current, but still listing the old.
3. We could store the referenced versions in Cordra instead of GITHUB - so we could redirect https://e-rihs.io/schema/* to point at a related resolver ....

Either way we need to update the https://e-rihs.io/schema landing page :-)

**Comment by kobbejager** [comment]
I adapted the Equipment and Software models for Cordra, and doing this I removed "method_statemement" . Solved!
